version: '3.7'

networks:
  node-app:

services:
  client:
    build:
      context: .
      dockerfile: ./Dockerfile
    networks:
      - node-app
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - "3000:3000"
    restart: always